"""Add currency to Payment

Revision ID: 46a33ff8bf06
Revises: 249e4806fa6e
Create Date: 2025-12-02 11:29:29.963828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a33ff8bf06'
down_revision: Union[str, Sequence[str], None] = '249e4806fa6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('currency', sa.String(length=10), nullable=False))
    op.drop_column('payments', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###
