"""Add customer id to user

Revision ID: 530eb38fb237
Revises: 46a33ff8bf06
Create Date: 2025-12-02 11:36:36.731243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530eb38fb237'
down_revision: Union[str, Sequence[str], None] = '46a33ff8bf06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customers_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'customers_id')
    # ### end Alembic commands ###
