"""Finish the models

Revision ID: a08687f96d4c
Revises: ed86cdd3ef78
Create Date: 2025-12-09 18:40:18.691440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a08687f96d4c'
down_revision: Union[str, Sequence[str], None] = 'ed86cdd3ef78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_plus_subscriber', sa.Boolean(), nullable=True))
    op.alter_column('users', 'customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=False)
    op.drop_column('users', 'customers_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customers_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.alter_column('users', 'customer_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('users', 'is_plus_subscriber')
    op.drop_column('users', 'stripe_subscription_id')
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey')),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('subscriptions_stripe_subscription_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###
