"""Add customerid to user

Revision ID: bb728805b517
Revises: dec1b597c139
Create Date: 2025-12-03 18:47:57.146542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb728805b517'
down_revision: Union[str, Sequence[str], None] = 'dec1b597c139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('customers_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('customer_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'customer_id')
    op.drop_column('users', 'customers_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
